version: '3'
services:
    postgres:
        image: postgres:13
        container_name: postgres-cont
        ports:
          - "5400:5432"
        environment:
            - LC_ALL=C.UTF-8
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
        volumes:
            - ./input_files/schema.sql:/docker-entrypoint-initdb.d/schema.sql
            # run postgres with custom config
            # get default config in terminal running
            # docker run -i --rm postgres cat /usr/share/postgresql/postgresql.conf.sample > my-postgres.conf
            #- ./postgres.conf:/etc/postgresql/postgresql.conf
            # create a data directory on the host system into which to
            # persist and store our data that is created in our database
            #- ./postgres_data:/var/lib/postgresql/data
    wildfly:
        image: tipitasa/dockerepo:latest
        container_name: wildfly-cont
        #build: .
        ports:
            - "8080:8080"
            - "9990:9990"
        depends_on:
            - postgres
        #volumes:
            #- $PWD/output_files/logs:/opt/jboss/wildfly/standalone/log

